name: build with node.js
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: set node version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm
      
      - name: npm ci
        run: npm ci

      - name: build site
        run: npm run build --if-present

      - name: run test
        run: npm test

